const strings: Record<string, Record<string, string>> = {
  en: {
    onboarding_detect_title: "Detects what's around you",
    onboarding_detect_subtitle: 'Objects, distances, and obstacles',
    onboarding_detect_tts: "EYES detects objects, distances, and obstacles around you using your phone's camera.",
    onboarding_how_title: 'Point → Tap → Listen',
    onboarding_how_subtitle: 'Simple three-step interaction',
    onboarding_how_tts: 'Point your camera at your surroundings. Tap the analyze button. Listen to the spoken result.',
    onboarding_feedback_title: 'Multiple Feedback Types',
    onboarding_feedback_subtitle: 'Voice and Vibration',
    onboarding_feedback_tts: 'Get feedback through voice descriptions and vibration patterns.',
    onboarding_privacy_title: 'Your privacy is protected',
    onboarding_privacy_subtitle: 'No images are saved or stored',
    onboarding_privacy_tts: 'Your privacy matters. No images are saved or stored on this device or any server.',
    skip: 'Skip',
    get_started: 'Get Started',
    next: 'Next',
    camera_ready: 'Camera ready. Tap to analyze.',
    analyzing: 'Analyzing your surroundings',
    starting_camera: 'Starting camera...',
    camera_unavailable: 'Camera unavailable',
    check_permissions: 'Please check camera permissions',
    last_result: 'Last:',
    auto_on: 'Auto: ON',
    auto: 'Auto',
    settings: 'Settings',
    appearance: 'APPEARANCE',
    theme: 'Theme',
    light: 'Light',
    dark: 'Dark',
    system: 'System',
    feedback: 'FEEDBACK',
    voice_feedback: 'Voice Feedback',
    vibration_feedback: 'Vibration Feedback',
    vibration_intensity: 'Vibration Intensity',
    light_intensity: 'Light',
    medium_intensity: 'Medium',
    strong_intensity: 'Strong',
    speech_rate: 'Speech Rate',
    scanning: 'SCANNING',
    auto_scan: 'Auto-Scan',
    scan_interval: 'Scan Interval',
    general: 'GENERAL',
    language: 'Language',
    english: 'English',
    filipino: 'Filipino',
    history: 'History',
    about: 'ABOUT',
    about_eyes: 'About EYES',
    version: 'Version',
    disable_voice_title: 'Disable Voice?',
    disable_voice_message: 'Voice is your primary feedback method. Are you sure?',
    cancel: 'Cancel',
    turn_off: 'Turn Off',
    about_title: 'About EYES',
    purpose: 'Purpose',
    technology: 'Technology',
    disclaimer: 'Disclaimer',
    developers: 'Developers',
    made_with_purpose: 'Made with purpose.',
    error_timeout: 'Request timed out. Please try again.',
    error_no_internet: 'No internet connection.',
    error_generic: 'Something went wrong. Please try again.',
    intro_response: "I am EYES, I help in seeing your surroundings. Point the camera and tap to scan so I can see your surroundings. I'll tell you what's in front of you, how far away, and point out dangers. I can also detect and count money. Just say 'scan' or tap the button to get started."
  },
  fil: {
    onboarding_detect_title: 'Nakaka-detect ng paligid mo',
    onboarding_detect_subtitle: 'Mga bagay, distansya, at hadlang',
    onboarding_detect_tts: 'Ang EYES ay nakaka-detect ng mga bagay, distansya, at hadlang sa iyong paligid gamit ang camera ng iyong telepono.',
    onboarding_how_title: 'Itutok → I-tap → Makinig',
    onboarding_how_subtitle: 'Simpleng tatlong hakbang',
    onboarding_how_tts: 'Itutok ang camera sa iyong paligid. I-tap ang analyze button. Makinig sa resulta.',
    onboarding_feedback_title: "Iba't ibang Uri ng Feedback",
    onboarding_feedback_subtitle: 'Boses at Vibration',
    onboarding_feedback_tts: 'Nagbibigay ang app ng impormasyon gamit ang speaker at vibrations ng telepono.',
    onboarding_privacy_title: 'Protektado ang iyong privacy',
    onboarding_privacy_subtitle: 'Walang mga litratong nai-save',
    onboarding_privacy_tts: 'Mahalaga ang iyong privacy. Walang mga litratong nai-save o naka-store sa device o sa anumang server.',
    skip: 'Laktawan',
    get_started: 'Magsimula',
    next: 'Susunod',
    camera_ready: 'Handa na ang camera. I-tap para tingnan o magsabi ng scan, i-scan, kunan, pakita, kuhanan.',
    analyzing: 'Pinagmamasdan ang iyong paligid',
    starting_camera: 'Binubuksan ang camera...',
    camera_unavailable: 'Hindi available ang camera',
    check_permissions: 'Pakisuri ang mga camera permission',
    last_result: 'Huling:',
    auto_on: 'Auto: ON',
    auto: 'Auto',
    settings: 'Mga Setting',
    appearance: 'HITSURA',
    theme: 'Tema',
    light: 'Maliwanag',
    dark: 'Madilim',
    system: 'Sistema',
    feedback: 'FEEDBACK',
    voice_feedback: 'Voice Feedback',
    vibration_feedback: 'Vibration Feedback',
    vibration_intensity: 'Lakas ng Vibration',
    light_intensity: 'Mahina',
    medium_intensity: 'Katamtaman',
    strong_intensity: 'Malakas',
    speech_rate: 'Bilis ng Pagsasalita',
    scanning: 'PAG-SCAN',
    auto_scan: 'Auto-Scan',
    scan_interval: 'Agwat ng Scan',
    general: 'PANGKALAHATAN',
    language: 'Wika',
    english: 'Ingles',
    filipino: 'Filipino',
    history: 'Kasaysayan',
    about: 'TUNGKOL SA',
    about_eyes: 'Tungkol sa EYES',
    version: 'Bersyon',
    disable_voice_title: 'I-disable ang Voice?',
    disable_voice_message: 'Ang voice ang pangunahing paraan ng feedback. Sigurado ka ba?',
    cancel: 'Kanselahin',
    turn_off: 'Patayin',
    about_title: 'Tungkol sa EYES',
    purpose: 'Layunin',
    technology: 'Teknolohiya',
    disclaimer: 'Disclaimer',
    developers: 'Mga Developer',
    made_with_purpose: 'Ginawa nang may layunin.',
    error_timeout: 'Nag-timeout ang request. Pakisubukang muli.',
    error_no_internet: 'Walang koneksyon sa internet.',
    error_generic: 'May nangyaring mali. Pakisubukang muli.',
    intro_response:"Ako si EYES tumutulong ako sa iyo na pagmasdan ang iyong paligid. Itutok ang camera at i-tap para suriin ko ang paligid. Sasabihin ko sa iyo kung ano ang nasa harap mo, kung gaano kalayo, at magsasabi ako ng mga panganib. Kaya ko ring makapag-detect at mag bilang ng pera. Sabihin lang ang 'suriin' o i-tap ang button para magsimula."
  },
};

export function t(key: string, language: string): string {
  return strings[language]?.[key] ?? strings['en']?.[key] ?? key;
}
